name: Workflow with multiple stages

on: push

jobs:
  job-on-ubuntu:
    # name is optional, one will not be used here
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: pwd
  job-on-windows:
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date
        # no name
      - run: ls
  dependent-job-1:
    needs: [job-on-ubuntu, job-on-windows]
    runs-on: macos-latest
    name: A job that runs on Mac after first two jobs
    steps:
      - run: pwd
      - name: new step
        run: ls
      - run: env
  dependent-job-2:
    needs: dependent-job-1
    runs-on: ubuntu-latest
    name: A final job
    steps:
      - run: echo This is the last job!
    
